version: 1.0.{build}
image: Visual Studio 2022
environment:
  nodejs_version: "18"
  GITHUB_TOKEN:
    secure: ${GITHUB_TOKEN}

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci
  - npm install gh-pages --save-dev

build_script:
  - npm run build

on_success:
  - git config --global user.email "appveyor@example.com"
  - git config --global user.name "AppVeyor CI"
  
  - ps: |
      $repoUrl = "https://$($env:GITHUB_TOKEN)@github.com/Vladislav-Proshchenkov/Gnome_Killer.git"
      cd dist
      git init
      git add .
      git commit -m "Auto-deploy [skip ci]"
      git push --force --quiet $repoUrl master:gh-pages

artifacts:
  - path: dist
    name: distribution