version: 1.0.{build}
image: Visual Studio 2022
environment:
  nodejs_version: "18"
  GITHUB_TOKEN:
    secure: ${GITHUB_TOKEN}

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci
  - npm install gh-pages --save-dev

build_script:
  - npm run build

on_success:
  - git config --global user.email "appveyor@example.com"
  - git config --global user.name "AppVeyor CI"
  
  - ps: |
      $credentialPath = "$env:USERPROFILE\.git-credentials"
      "https://$($env:GITHUB_TOKEN):x-oauth-basic@github.com" | Out-File -FilePath $credentialPath -Encoding ascii
      git config --global credential.helper store
  
  - npm run deploy

artifacts:
  - path: dist
    name: distribution