version: 1.0.{build}
image: Visual Studio 2022
environment:
  nodejs_version: "18"
  CI: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g gh-pages@latest

build_script:
  - npm run build

artifacts:
  - path: dist
    name: distribution

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_token):x-oauth-basic@github.com`n"
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - npm run deploy

deploy:
  provider: GitHub
  description: 'Automatic deploy to GitHub Pages'
  auth_token:
    secure: YOUR_ENCRYPTED_GITHUB_TOKEN
  on:
    branch: main
  skip_cleanup: true
  draft: false